### ISSUE TITLE
missing AppModuleNgFactory

### ISSUE THREAD

**Issue by arambekverdyan** [samteb/Angular-7-Webpack-4#1]
The main.aot.ts has a dependency to `'./app/app.module.ngfactory'` but there is no such a file in this directory

**Comment by samteb** [comment]
At compilation time, `AppModuleFactory` exists !

In AOT compilation, the Angular compiler generates many files in order to compile your application before it is shipped to the browser and one of them is `AppModuleFactory`.

To stay clean, and because we are in production, I delete all these files after all the bundles are generated. This is only for this reason that you don't see it !

Try to remove `npm run build:clean` from `build:prod` script inside `package.json` and you will see it !

**Comment by Pablodotnet** [comment]
This is causing not compiling on dev, I don't know why but it throws me the error that AppModuleNgFactory does not exist (and it is right) I'm running npm run build:dev and at the end is not compiling due to the lack of this file...
